#!/bin/bash

EXPECTED_ARGS=1
E_BADARGS=65

if [ $# -ne $EXPECTED_ARGS ]
then
  echo "Usage: `basename $0` FILE"
  exit $E_BADARGS
fi

enc_filename=$1
dec_filename=`echo $enc_filename | sed 's/\./ /g' | awk '{print $1"."$2}'`
final_filename=`echo $enc_filename | sed 's/\./ /g' | awk '{print $1}'`

echo "Decrypting file..."
openssl aes-256-cbc -d -in $enc_filename -out $dec_filename
echo "File decrypted. Decompressing..."
tar xzf $dec_filename
echo "File decrypted."
RESULT=$?

rm $dec_filename

if [ $RESULT -ne 0 ]
then
    echo "Error encrypting"
    exit 1
fi
rm -rf $enc_filename

